spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/springboot_db
        username: springuser
        password: springpassword
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
management:
    endpoint:
        health:
            show-details: never